apply plugin: 'com.android.application'
apply plugin: 'de.mannodermaus.android-junit5'
apply plugin: 'org.sonarqube'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.devtools.ksp'

android {
    compileSdk 36

    defaultConfig {
        applicationId "coolpharaoh.tee.speicher.tea.timer"
        minSdk 32
        targetSdk 36
        versionCode 204
        versionName "4.5"
        // androidTest
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: 'true'

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    testOptions {
        unitTests.includeAndroidResources = true
        // Return default values for CountDownTimer
        unitTests.returnDefaultValues = true
        unitTests.all {
            // Configure whether failing tests should fail the build
            ignoreFailures false

            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
            }
        }
        //execution 'ANDROIDX_TEST_ORCHESTRATOR' only need if the database needs to be cleaned
    }
    namespace 'coolpharaoh.tee.speicher.tea.timer'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.activity:activity-ktx:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.documentfile:documentfile:1.1.0'
    implementation 'androidx.work:work-runtime:2.11.2'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'
    implementation 'com.google.android.play:asset-delivery-ktx:2.3.0'
    implementation 'com.google.android.play:feature-delivery-ktx:2.1.0'
    implementation 'com.google.android.play:review-ktx:2.0.2'
    implementation 'com.google.android.play:app-update-ktx:2.1.0'
    // room
    implementation 'androidx.room:room-runtime:2.8.4'
    ksp 'androidx.room:room-compiler:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.11.0'
    // test
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'
    testImplementation 'junit:junit:4.13.2'                         //needed for junit4 only
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine:5.11.3'  //needed for junit4 only
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation "io.mockk:mockk:1.14.11"
    testImplementation 'org.robolectric:robolectric:4.16.1'
    testImplementation 'androidx.test:core:1.7.0'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
    testImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    testImplementation 'androidx.test.espresso:espresso-intents:3.7.0'
    // androidTest
    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'org.assertj:assertj-core:3.27.7'
    androidTestImplementation 'org.hamcrest:hamcrest-library:3.0'
    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.7.0'
    androidTestUtil 'androidx.test:orchestrator:1.6.1'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'com.github.QuadFlask:colorpicker:0.0.15'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    ksp 'com.github.bumptech.glide:compiler:4.16.0'
    // gson
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
}

tasks.register("testAll") {
    dependsOn = ['test', 'connectedAndroidTest']
    group = 'custom_tasks'
    description = "Run all tests"
}
